(function(){
const DEFAULT_ITEMS=["설비주위에 물건, 전선 정리는 되어 있는가?","작업대는 정리가 되어 있는가?","작업지도서 등 현장부착물 잘 되어 있는가?","작업대는 작업하기 편하게 정돈 되어 있는가?","설비 점검 및 주변청소는 잘 되어 있는가?","바닥에 기름이나 물은 청소 되었는가?","오일 누수 및 파손 될 결함은 없는가?","각종 유류는 눈으로 보는 관리가 되고 있는가?","작업자의 작업복 및 안전복장은 갖추었는가?","게시물은 잘 관리되고 있는가?"];
function defaults(){return DEFAULT_ITEMS.map((name,i)=>({no:i+1,active:true,name}))}
function ensureItems(){if(!settings.items||settings.items.length!==10)settings.items=defaults();settings.items.forEach((x,i)=>{x.no=i+1;if(typeof x.active==='undefined')x.active=true;if(!x.name)x.name=DEFAULT_ITEMS[i]});settings.items.forEach((x,i)=>itemNames[i]=x.name)}
function isSampleAdminSettings(){if(!settings)return true;const sampleMail=(settings.mails||[]).some(x=>/ceo@samjinlnd\.co\.kr|manager@samjinlnd\.co\.kr/i.test(x.email||''));const sampleOwner=(settings.machines||[]).some(x=>['홍길동','김철수','이민수','박지훈','최영호','정다은','오세훈','강민재','한지훈','윤서준'].includes(x.owner));return sampleMail||sampleOwner}
async function loadItems(){try{const r=await fetch(WEB_APP_URL+'?action=get_items&_='+Date.now(),{cache:'no-store'}),o=await r.json();if(o&&o.status==='success'&&Array.isArray(o.items)){settings.items=DEFAULT_ITEMS.map((d,i)=>{const x=o.items.find(v=>Number(v.no)===i+1)||{};return {no:i+1,active:x.active!==false,name:String(x.name||d).trim()||d}});settings.items.forEach((x,i)=>itemNames[i]=x.name);localStorage.setItem('mymachine_v3_settings',JSON.stringify(settings));return true}}catch(e){console.warn('점검항목 조회 실패',e)}return false}
async function loadAdminSettings(){try{const r=await fetch(WEB_APP_URL+'?action=get_admin_settings&_='+Date.now(),{cache:'no-store'}),o=await r.json();if(o&&o.status==='success'&&o.settings){const s=o.settings;if(s.configured){settings.machines=Array.isArray(s.machines)?s.machines:[];settings.mails=Array.isArray(s.mails)?s.mails:[];localStorage.setItem('mymachine_v3_settings',JSON.stringify(settings));return true}if(!isSampleAdminSettings()&&((settings.machines||[]).length||(settings.mails||[]).length)){await saveAdminSettings();return true}settings.machines=[];settings.mails=[];localStorage.setItem('mymachine_v3_settings',JSON.stringify(settings));return false}}catch(e){console.warn('관리자 설정 조회 실패',e)}return false}
async function saveAdminSettings(){const r=await fetch(WEB_APP_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save_admin_settings',machines:settings.machines||[],mails:settings.mails||[]})});const o=await r.json();if(!o||o.status!=='success')throw new Error(o&&o.message||'설비/메일 설정 저장 실패');return true}
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}
function installUI(){ensureItems();const panel=document.querySelector('#adminPanelModal .grid3');if(panel&&!document.getElementById('btnItemSettings')){const b=document.createElement('button');b.id='btnItemSettings';b.className='btn primary';b.textContent='점검항목 설정';b.onclick=()=>openSettings('item');panel.insertBefore(b,panel.children[1]||null)}const tabs=settingsModal.querySelector('.modalInner>div:nth-child(2)');if(tabs)tabs.style.display='none';if(!document.getElementById('itemSection')){const s=document.createElement('div');s.id='itemSection';s.style.display='none';s.innerHTML='<p class="hint">점검 문구를 직접 수정하거나 사용 체크를 해제하면 작업자 휴대폰에서 해당 항목이 숨겨집니다. 번호 1~10은 데이터 호환을 위해 유지됩니다.</p><div id="itemSettings"></div><button class="btn" id="resetItemsBtn">점검항목 기본값 복원</button>';mailSection.parentNode.insertBefore(s,mailSection);document.getElementById('resetItemsBtn').onclick=()=>{if(confirm('점검항목을 기본값으로 복원할까요?')){settings.items=defaults();settings.items.forEach((x,i)=>itemNames[i]=x.name);renderSettings()}}}const st=document.createElement('style');st.textContent='.itemSettingRow{display:grid;grid-template-columns:70px 70px 1fr;gap:6px;margin-bottom:6px;align-items:center}';document.head.appendChild(st)}
const baseRender=renderSettings;renderSettings=function(){ensureItems();baseRender();if(window.itemSettings)itemSettings.innerHTML='<div class="itemSettingRow"><div class="rowHead">사용</div><div class="rowHead">번호</div><div class="rowHead">점검 내용</div></div>'+settings.items.map((x,i)=>`<div class="itemSettingRow"><div style="text-align:center"><input class="check" type="checkbox" ${x.active!==false?'checked':''} data-item="${i}" data-k="active"></div><div style="text-align:center;font-weight:900">${i+1}</div><input value="${esc(x.name)}" data-item="${i}" data-k="name"></div>`).join('')}
const baseCollect=collectSettings;collectSettings=function(){baseCollect();document.querySelectorAll('[data-item]').forEach(el=>{settings.items[+el.dataset.item][el.dataset.k]=el.type==='checkbox'?el.checked:el.value.trim()});settings.items.forEach((x,i)=>itemNames[i]=x.name||DEFAULT_ITEMS[i])}
openSettings=async function(tab='machine'){if(!isAdminAuthed())return openAdminLogin();if(tab==='item')await loadItems();else await loadAdminSettings();renderSettings();showSettingsTab(tab);settingsModal.style.display='flex'}
showSettingsTab=function(t){machineSection.style.display=t==='machine'?'block':'none';mailSection.style.display=t==='mail'?'block':'none';if(window.itemSection)itemSection.style.display=t==='item'?'block':'none';settingsTitle.textContent=t==='mail'?'메일 수신자 설정':t==='item'?'점검항목 설정':'설비 마스터 설정'}
const baseSave=saveSettings;saveSettings=async function(){collectSettings();if(!settings.items.some(x=>x.active!==false))return alert('점검항목은 최소 1개 이상 사용해야 합니다.');try{localStorage.setItem('mymachine_v3_settings',JSON.stringify(settings));await saveAdminSettings();const r=await fetch(WEB_APP_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save_items',items:settings.items})}),o=await r.json();if(!o||o.status!=='success')throw new Error(o&&o.message||'점검항목 저장 실패');alert('설정 저장 완료\n설비/메일/점검항목이 서버에 영구 저장되었습니다.');closeSettings();compute()}catch(e){alert('설정 저장 실패\n'+e.message)}}
function snapshot(v){try{return Array.isArray(v)?v:(typeof v==='string'&&v?JSON.parse(v):null)}catch(e){return null}}
window.itemNameForRow=function(r,n){const s=r.itemNamesSnapshotParsed||snapshot(r.itemNamesSnapshot);if(Array.isArray(s)){const x=s.find(v=>Number(v.no)===Number(n));if(x&&x.name)return x.name}return itemNames[n-1]||DEFAULT_ITEMS[n-1]||''}
normalizeRow=function(r,i){let items=Array.from({length:10},(_,k)=>r['item'+(k+1)]||(r.items&&r.items[k])||'O'),actions=parseActions(r),x=items.map((v,k)=>v==='X'?k+1:null).filter(Boolean),app=items.filter(v=>v!=='N/A'&&v!=='').length||10,sc=Math.max(0,Math.round((app-x.length)/app*100));return {...r,date:(r.date||r.inspectDate||todayStr).toString().slice(0,10),machine:r.machine||r.machineId||'',inspector:r.inspector||r.inspectorName||'',items,xItems:x.join(','),xCount:x.length,score:sc+'점',issue:r.issue||r.issueRemarks||'',actions,photos:r.photos||[],itemNamesSnapshotParsed:snapshot(r.itemNamesSnapshot),rowIndex:r.rowIndex||i+2}}
renderRequests=function(){requestBody.innerHTML=requests.map(q=>`<tr><td>${q.id}</td><td>${q.row.date}</td><td>${q.row.machine}</td><td>${q.item}. ${itemNameForRow(q.row,q.item)}</td><td>${q.row.inspector}</td><td>${q.priority}</td><td class="left">${q.text||'-'}</td><td><span class="badge ${q.status==='완료'?'b-green':q.status==='진행중'?'b-blue':'b-orange'}">${q.status}</span></td><td class="noPrint"><button class="btn" onclick="setReqStatus('${q.id}','진행중')">진행</button><button class="btn green" onclick="setReqStatus('${q.id}','완료')">완료</button></td></tr>`).join('')||'<tr><td colspan="9">개선요청 없음</td></tr>'}
const oldDetails=renderDetails;renderDetails=function(){oldDetails();document.querySelectorAll('#detailBody tr').forEach(tr=>{const cells=tr.children;if(cells.length>4){const m=(cells[4].textContent||'').match(/^(\d+)\./);if(m){const n=+m[1],row=reportRows.find(r=>r.date===cells[1].textContent&&r.machine===cells[2].textContent);if(row)cells[4].textContent=n+'. '+itemNameForRow(row,n)}}})}
const oldLoad=loadRealData;loadRealData=async function(btn){await Promise.all([loadItems(),loadAdminSettings()]);return oldLoad(btn)}
installUI();Promise.all([loadItems(),loadAdminSettings()]).then(()=>{try{renderSettings()}catch(e){console.warn(e)}});
})();