const WEB_APP_URL='https://script.google.com/macros/s/AKfycbwgEHiICS2ga2XCuVYppgEGCJgJ3rAjA2jnq8Qbk1-Ol7zpwe5r2wnSw00M-ovNEB2i/exec';
const DEF=["설비주위에 물건, 전선 정리는 되어 있는가?","작업대는 정리가 되어 있는가?","작업지도서 등 현장부착물 잘 되어 있는가?","작업대는 작업하기 편하게 정돈 되어 있는가?","설비 점검 및 주변청소는 잘 되어 있는가?","바닥에 기름이나 물은 청소 되었는가?","오일 누수 및 파손 될 결함은 없는가?","각종 유류는 눈으로 보는 관리가 되고 있는가?","작업자의 작업복 및 안전복장은 갖추었는가?","게시물은 잘 관리되고 있는가?"];
let cfg=DEF.map((name,i)=>({no:i+1,active:true,name})),photoData={};
function settings(){try{return JSON.parse(localStorage.getItem('mymachine_v3_settings'))||{machines:[]}}catch(e){return {machines:[]}}}
function initMachines(){let ms=(settings().machines||[]).filter(x=>x.active!==false);if(!ms.length)ms=Array.from({length:20},(_,i)=>({machine:'PRESS-'+String(i+1).padStart(2,'0')}));machineId.innerHTML='<option value="">담당 설비 선택</option>'+ms.map(m=>`<option value="${m.machine}">${m.machine}${m.maker?' / '+m.maker:''}${m.ton?' / '+m.ton:''}${m.owner?' / 담당 '+m.owner:''}</option>`).join('')}
async function loadItems(){try{let r=await fetch(WEB_APP_URL+'?action=get_items&_='+Date.now(),{cache:'no-store'}),o=await r.json();if(o&&o.status==='success'&&Array.isArray(o.items))cfg=DEF.map((d,i)=>{let x=o.items.find(v=>+v.no===i+1)||{};return {no:i+1,active:x.active!==false,name:String(x.name||d).trim()||d}})}catch(e){console.warn(e)}render()}
function active(){return cfg.filter(x=>x.active!==false)}
function pbtn(n,k){let id=n+'_'+k;return `<div class="photos"><label class="pbtn" for="cam_${id}">📷 촬영</label><label class="pbtn" for="gal_${id}">🖼 앨범</label></div><input type="file" id="cam_${id}" accept="image/*" capture="environment" onchange="image(this,'${id}')"><input type="file" id="gal_${id}" accept="image/*" onchange="image(this,'${id}')"><img class="prev" id="prev_${id}">`}
function render(){items.innerHTML=active().map(x=>{let n=x.no;return `<div class="item" id="card${n}"><div class="top"><div>${n}. ${x.name}</div><span class="badge" id="state${n}">미선택</span></div><div class="choice"><label class="good" id="ok${n}"><input type="radio" name="item${n}" value="O" onchange="setItem(${n},'O')">✅ 양호</label><label class="bad" id="ng${n}"><input type="radio" name="item${n}" value="X" onchange="setItem(${n},'X')">⚠ 미흡</label></div><div class="actbox" id="actbox${n}"><b>미흡 처리 구분</b><div class="acts"><label class="imm" id="imm${n}"><input type="radio" name="act${n}" value="immediate" onchange="setAct(${n},'immediate')">즉시개선<br><span class="hint">작업자 조치완료</span></label><label class="req" id="req${n}"><input type="radio" name="act${n}" value="request" onchange="setAct(${n},'request')">개선요청<br><span class="hint">전문인력 조치</span></label></div><div id="immbox${n}" style="display:none"><label>즉시개선 내용</label><textarea id="immtxt${n}" rows="2"></textarea><div class="photos"><div><label>개선 전 사진</label>${pbtn(n,'immBefore')}</div><div><label>개선 후 사진</label>${pbtn(n,'immAfter')}</div></div></div><div id="reqbox${n}" style="display:none"><label>개선 요청 내용</label><textarea id="reqtxt${n}" rows="2"></textarea><label>우선순위</label><select id="priority${n}"><option>보통</option><option>긴급</option><option>낮음</option></select><label>미흡 사진</label>${pbtn(n,'reqBefore')}</div></div></div>`}).join('')}
function sel(name){let e=document.querySelector(`input[name="${name}"]:checked`);return e?e.value:''}
function setItem(n,v){let card=document.getElementById('card'+n),ok=document.getElementById('ok'+n),ng=document.getElementById('ng'+n);card.classList.remove('ok','ng');ok.classList.toggle('sel',v==='O');ng.classList.toggle('sel',v==='X');card.classList.add(v==='O'?'ok':'ng');document.getElementById('state'+n).textContent=v==='O'?'양호':'미흡';document.getElementById('actbox'+n).style.display=v==='X'?'block':'none'}
function setAct(n,v){document.getElementById('imm'+n).classList.toggle('sel',v==='immediate');document.getElementById('req'+n).classList.toggle('sel',v==='request');document.getElementById('immbox'+n).style.display=v==='immediate'?'block':'none';document.getElementById('reqbox'+n).style.display=v==='request'?'block':'none'}
function image(input,key){if(!input.files?.[0])return;let rd=new FileReader();rd.onload=e=>{let im=new Image();im.onload=()=>{let c=document.createElement('canvas'),max=1200,w=im.width,h=im.height;if(w>h&&w>max){h=Math.round(h*max/w);w=max}else if(h>max){w=Math.round(w*max/h);h=max}c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);let d=c.toDataURL('image/jpeg',.78);photoData[key]={mimeType:'image/jpeg',base64:d.split(',')[1],preview:d};let p=document.getElementById('prev_'+key);p.src=d;p.style.display='block'};im.src=e.target.result};rd.readAsDataURL(input.files[0])}
async function submitData(){let d={inspectDate:inspectDate.value,inspectorName:inspectorName.value.trim(),machineId:machineId.value,issueRemarks:issueRemarks.value.trim(),photos:[],itemActions:[]};if(!d.inspectDate||!d.inspectorName||!d.machineId)return alert('일자, 점검자, 담당 설비를 입력하세요.');let miss=[],used=new Set(active().map(x=>x.no));for(let n=1;n<=10;n++){if(!used.has(n)){d['item'+n]='N/A';continue}let v=sel('item'+n);if(!v)miss.push(n);d['item'+n]=v;if(v==='X'){let a=sel('act'+n);if(!a)return alert(n+'번 미흡 항목의 처리 구분을 선택하세요.');let o={item:n,type:a,status:a==='immediate'?'조치완료':'개선요청',priority:a==='request'?document.getElementById('priority'+n).value:'',text:a==='immediate'?document.getElementById('immtxt'+n).value.trim():document.getElementById('reqtxt'+n).value.trim(),photos:{}};['immBefore','immAfter','reqBefore'].forEach(k=>{let p=photoData[n+'_'+k];if(p){o.photos[k]=p;d.photos.push(p)}});if(a==='immediate'&&(!o.photos.immBefore||!o.photos.immAfter)&&!confirm(n+'번 전/후 사진이 부족합니다. 그래도 등록할까요?'))return;if(a==='request'&&!o.text)return alert(n+'번 개선요청 내용을 입력하세요.');d.itemActions.push(o)}}if(miss.length)return alert('미선택 항목: '+miss.join(', '));d.itemActionsJson=JSON.stringify(d.itemActions);d.itemNamesSnapshot=JSON.stringify(cfg);d.immediateCount=d.itemActions.filter(x=>x.type==='immediate').length;d.requestCount=d.itemActions.filter(x=>x.type==='request').length;d.actionCompleteCount=d.immediateCount;d.xCount=Object.keys(d).filter(k=>/^item\d+$/.test(k)&&d[k]==='X').length;if(!confirm(`점검 결과를 등록할까요?\n미흡: ${d.xCount}건\n즉시개선: ${d.immediateCount}건\n개선요청: ${d.requestCount}건`))return;let b=document.querySelector('.submit');b.disabled=true;b.textContent='등록 중...';try{let r=await fetch(WEB_APP_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(d)}),o=await r.json();if(o.status!=='success')throw Error(o.message||'등록 실패');alert('등록 완료');location.reload()}catch(e){alert('등록 오류: '+e.message);b.disabled=false;b.textContent='점검 결과 등록'}}
inspectDate.valueAsDate=new Date();initMachines();loadItems();